# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generate the kernel's build identifier: the source tree's git commit, with
# "-dirty" for uncommitted changes, so every UART log says which build is
# running. Runs at build time (cmake -P), so a rebuild after a pull or a
# commit picks up the new commit without reconfiguring. The output is only
# rewritten when the identifier changes, so an unchanged tree does not relink.
#
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<file.c> -P build-id.cmake

execute_process(
    COMMAND git -C "${SOURCE_DIR}" describe --always --dirty --abbrev=7
    OUTPUT_VARIABLE build_id
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR build_id STREQUAL "")
    set(build_id "unknown")  # not a git checkout (a source tarball)
endif()

set(content "// Generated by cmake/build-id.cmake. Do not edit.\nconst char koraos_build_id[] = \"${build_id}\";\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
else()
    set(previous "")
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
